[default]
# Grid
grid_width = 25  # px
grid_height = 15  # px
tile_width = 64  # px
tile_height = 64  # px
road_width = 32  # px
# Traffic
vehicle_stop_wait_time = 0.5  # sec
intersection_clear_time = 0.35  # sec
# Graphics
randomize_vehicle_color = false
vehicle_radius = 4
# Testing
stress_test = false

    [default.debug]
    display_travel_edges = false


[development]
# Graphics
randomize_vehicle_color = true
# Testing
stress_test = false

    [development.debug]
    display_travel_edges = true

[production]
